# Generated by Django 5.2.17 on 2026-09-30 12:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('register', 'Register'), ('email_verified', 'Email Verified'), ('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('account_locked', 'Account Locked'), ('logout', 'Logout'), ('token_refresh', 'Token Refresh'), ('password_reset_requested', 'Password Reset Requested'), ('password_reset_done', 'Password Reset Done'), ('mfa_enrolled', 'Mfa Enrolled'), ('mfa_success', 'Mfa Success'), ('mfa_failed', 'Mfa Failed'), ('google_login', 'Google Login')], max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_events', to='accounts.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='audit_authe_tenant__8b6142_idx'), models.Index(fields=['user', '-created_at'], name='audit_authe_user_id_7ee947_idx'), models.Index(fields=['event_type', '-created_at'], name='audit_authe_event_t_8c8444_idx')],
            },
        ),
    ]
